INSERT INTO GUESTBOOK(IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
    VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍일동', '제목1', '내용1', 'hong@test.com', '1111', SYSDATE - 3);

INSERT INTO GUESTBOOK(IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
    VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍이동', '제목2', '내용2', 'hong@test.com', '2222', SYSDATE - 2);
    
INSERT INTO GUESTBOOK(IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
    VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍삼동', '제목3', '내용3', 'hong@test.com', '3333', SYSDATE - 1);
COMMIT;
SELECT * FROM GUESTBOOK;